"""Viser viewer for DUSt3R scene reconstructions and human motion."""

from __future__ import annotations

import pickle
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import tyro
import viser
from scipy.spatial.transform import Rotation as R


@dataclass
class Options:
    scene_pkl: Path = Path("outputs/dust3r_demo/scene.pkl")
    """Pickle generated by a Trophies DUSt3R reconstruction or alignment command."""

    max_views: Optional[int] = None
    """Optional cap on rendered views."""

    confidence_threshold: float = 0.0
    """Keep DUSt3R points with confidence above this threshold."""

    use_scene_mask: bool = True
    """Apply DUSt3R confidence mask; disable to inspect lower-confidence geometry."""

    point_size: float = 0.008
    """Initial point size."""

    human_motion_dir: Optional[Path] = None
    """Optional human-motion output directory with camera.npy and hps/hps_track_*.npy."""

    smpl_model_dir: Path = Path("body_models/smpl")
    """SMPL model directory used to turn human-motion outputs into meshes."""

    show_smpl_meshes: bool = True
    """Load and display SMPL meshes when hps files are available."""

    mesh_sample_stride: int = 30
    """Frame stride for sampled SMPL meshes in the static viewer."""

    mesh_max_tracks: Optional[int] = None
    """Optional maximum number of human tracks to render as meshes."""

    mesh_max_frames_per_track: Optional[int] = 8
    """Optional maximum sampled mesh frames per track."""

    show_human_points: bool = False
    """Also show human translation points for debugging."""

    human_point_size: float = 0.035
    """Initial point size for human trajectory centers."""

    camera_traj_point_size: float = 0.02
    """Initial point size for camera trajectory centers."""

    display_frame: str = "auto"
    """Display coordinate frame: auto, world, or dust3r. Sim(3)-aligned scenes use world."""

    host: str = "127.0.0.1"
    """Network interface for the Viser server; use SSH port forwarding remotely."""

    port: int = 8080
    """TCP port for the Viser server."""



def _load_scene(scene_pkl: Path) -> Tuple[Dict[str, object], Dict[str, Dict[str, np.ndarray]]]:
    if not scene_pkl.exists():
        raise FileNotFoundError(f"Scene pickle not found: {scene_pkl}")
    with scene_pkl.open("rb") as f:
        payload = pickle.load(f)
    env = payload.get("dust3r_ga_output")
    if not isinstance(env, dict) or not env:
        raise ValueError("dust3r_ga_output missing or empty in scene pickle")
    return payload, env


def _display_rotation(display_frame: str, payload: Dict[str, object], has_motion_overlay: bool) -> Tuple[str, np.ndarray]:
    mode = display_frame.lower().strip()
    if mode == "auto":
        if "alignment" in payload or has_motion_overlay:
            mode = "world"
        else:
            mode = "dust3r"
    if mode == "world":
        return mode, np.eye(3, dtype=np.float32)
    if mode == "dust3r":
        rot = np.eye(3, dtype=np.float32)
        rot[1, 1] = -1
        rot[2, 2] = -1
        return mode, rot
    raise ValueError(f"Unsupported display_frame '{display_frame}'. Expected auto, world, or dust3r.")


def _as_numpy(value: object) -> np.ndarray:
    if hasattr(value, "detach"):
        value = value.detach().cpu().numpy()
    return np.asarray(value)


def _load_camera_dict(human_motion_dir: Path) -> Optional[Dict[str, np.ndarray]]:
    camera_path = human_motion_dir / "camera.npy"
    if not camera_path.exists():
        return None
    data = np.load(camera_path, allow_pickle=True)
    return data.item() if not isinstance(data, np.lib.npyio.NpzFile) else {key: data[key] for key in data.files}


def _load_motion_camera(human_motion_dir: Path) -> Optional[np.ndarray]:
    camera = _load_camera_dict(human_motion_dir)
    if camera is None or "world_cam_T" not in camera:
        return None
    centers = np.asarray(camera["world_cam_T"], dtype=np.float32)
    keep = np.isfinite(centers).all(axis=1)
    return centers[keep]


def _load_human_tracks(human_motion_dir: Path) -> List[Tuple[str, np.ndarray]]:
    hps_dir = human_motion_dir / "hps"
    if not hps_dir.exists():
        return []

    tracks: List[Tuple[str, np.ndarray]] = []
    for path in sorted(hps_dir.glob("hps_track_*.npy")):
        data = np.load(path, allow_pickle=True).item()
        if "pred_trans" not in data:
            continue
        positions = _as_numpy(data["pred_trans"]).reshape(-1, 3).astype(np.float32)
        keep = np.isfinite(positions).all(axis=1)
        positions = positions[keep]
        if len(positions):
            tracks.append((path.stem, positions))
    return tracks


def _palette() -> np.ndarray:
    return np.array(
        [
            [255, 56, 48],
            [34, 197, 94],
            [245, 158, 11],
            [168, 85, 247],
            [236, 72, 153],
            [20, 184, 166],
            [234, 179, 8],
        ],
        dtype=np.uint8,
    )


def _load_smpl_meshes(
    human_motion_dir: Path,
    smpl_model_dir: Path,
    sample_stride: int,
    max_tracks: Optional[int],
    max_frames_per_track: Optional[int],
) -> List[Tuple[str, np.ndarray, np.ndarray, Tuple[int, int, int]]]:
    camera = _load_camera_dict(human_motion_dir)
    hps_dir = human_motion_dir / "hps"
    if camera is None or not hps_dir.exists():
        return []
    if "world_cam_R" not in camera or "world_cam_T" not in camera:
        return []

    import torch
    import smplx

    device = "cuda" if torch.cuda.is_available() else "cpu"
    smpl = smplx.SMPL(model_path=str(smpl_model_dir), gender="neutral", batch_size=1).to(device)
    faces = np.asarray(smpl.faces, dtype=np.int32)
    world_r = torch.tensor(np.asarray(camera["world_cam_R"]), dtype=torch.float32, device=device)
    world_t = torch.tensor(np.asarray(camera["world_cam_T"]), dtype=torch.float32, device=device)

    meshes: List[Tuple[str, np.ndarray, np.ndarray, Tuple[int, int, int]]] = []
    colors = _palette()
    hps_files = sorted(hps_dir.glob("hps_track_*.npy"))
    if max_tracks is not None:
        hps_files = hps_files[:max_tracks]

    stride = max(1, int(sample_stride))
    with torch.no_grad():
        for track_idx, hps_path in enumerate(hps_files):
            pred_smpl = np.load(hps_path, allow_pickle=True).item()
            required = {"pred_rotmat", "pred_shape", "pred_trans", "frame"}
            if not required.issubset(pred_smpl):
                continue

            frame = _as_numpy(pred_smpl["frame"]).astype(np.int64)
            selected = np.arange(0, len(frame), stride, dtype=np.int64)
            if max_frames_per_track is not None:
                selected = selected[: max(0, int(max_frames_per_track))]
            if selected.size == 0:
                continue

            frame_sel = frame[selected]
            valid = (frame_sel >= 0) & (frame_sel < len(world_t))
            selected = selected[valid]
            frame_sel = frame_sel[valid]
            if selected.size == 0:
                continue

            pred_rotmat = torch.as_tensor(_as_numpy(pred_smpl["pred_rotmat"])[selected], dtype=torch.float32, device=device)
            pred_shape_all = torch.as_tensor(_as_numpy(pred_smpl["pred_shape"]), dtype=torch.float32, device=device)
            mean_shape = pred_shape_all.mean(dim=0, keepdim=True).repeat(len(selected), 1)
            pred_trans = torch.as_tensor(_as_numpy(pred_smpl["pred_trans"])[selected], dtype=torch.float32, device=device).reshape(len(selected), 3)

            pred = smpl(
                body_pose=pred_rotmat[:, 1:],
                global_orient=pred_rotmat[:, [0]],
                betas=mean_shape,
                transl=pred_trans,
                pose2rot=False,
            )
            verts = pred.vertices
            cam_r = world_r[torch.as_tensor(frame_sel, dtype=torch.long, device=device)]
            cam_t = world_t[torch.as_tensor(frame_sel, dtype=torch.long, device=device)]
            verts_world = torch.einsum("bij,bnj->bni", cam_r, verts) + cam_t[:, None]
            verts_np = verts_world.detach().cpu().numpy().astype(np.float32)

            color = tuple(int(v) for v in colors[track_idx % len(colors)])
            for local_idx, video_frame in enumerate(frame_sel.tolist()):
                meshes.append((f"{hps_path.stem}_frame_{video_frame:04d}", verts_np[local_idx], faces, color))
    return meshes


def _flatten_points(
    entry: Dict[str, np.ndarray],
    confidence_threshold: float,
    use_scene_mask: bool,
) -> Tuple[np.ndarray, np.ndarray]:
    pts = np.asarray(entry["pts3d"])
    if pts.ndim == 3:
        pts = pts.reshape(-1, 3)

    colors = np.asarray(entry["rgbimg"]).reshape(-1, 3)
    if colors.dtype.kind in {"u", "i"} or colors.max(initial=0) > 1.0:
        colors = colors.astype(np.float32) / 255.0

    keep = np.isfinite(pts).all(axis=1)
    mask = entry.get("msk")
    if use_scene_mask and mask is not None:
        keep &= np.asarray(mask).reshape(-1).astype(bool)
    human_mask = entry.get("human_msk")
    if human_mask is not None:
        keep &= ~np.asarray(human_mask).reshape(-1).astype(bool)
    conf = entry.get("conf")
    if conf is not None:
        keep &= np.asarray(conf).reshape(-1) > confidence_threshold

    return pts[keep].astype(np.float32), colors[keep].astype(np.float32)


def _camera_pose(entry: Dict[str, np.ndarray], display_rot: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    cam = np.asarray(entry["cam2world"]).copy()
    cam[:3, :3] = display_rot @ cam[:3, :3]
    cam[:3, 3] = cam[:3, 3] @ display_rot
    quat_xyzw = R.from_matrix(cam[:3, :3]).as_quat()
    quat_wxyz = np.concatenate([quat_xyzw[3:], quat_xyzw[:3]])
    return quat_wxyz, cam[:3, 3]



def visualize(opts: Options) -> None:
    payload, env = _load_scene(opts.scene_pkl)

    server = viser.ViserServer(host=opts.host, port=opts.port)
    server.scene.world_axes.visible = True
    server.scene.set_up_direction("+y")

    display_mode, display_rot = _display_rotation(opts.display_frame, payload, opts.human_motion_dir is not None)
    print(f"Display frame: {display_mode}")

    point_handles: List[viser.PointCloudHandle] = []
    camera_handles: List[object] = []
    motion_handles: List[viser.PointCloudHandle] = []
    mesh_handles: List[object] = []

    for idx, (name, entry) in enumerate(sorted(env.items())):
        if opts.max_views is not None and idx >= opts.max_views:
            break

        points, colors = _flatten_points(entry, opts.confidence_threshold, opts.use_scene_mask)
        if len(points) > 0:
            display_points = points @ display_rot
            point_handles.append(
                server.scene.add_point_cloud(
                    f"/dust3r/{name}/points",
                    points=display_points,
                    colors=colors,
                    point_size=opts.point_size,
                    point_shape="circle",
                )
            )

        quat, pos = _camera_pose(entry, display_rot)
        camera_handles.append(
            server.scene.add_frame(
                f"/dust3r/{name}/camera",
                wxyz=quat,
                position=pos,
                show_axes=True,
                axes_length=0.25,
                axes_radius=0.015,
            )
        )

    if opts.human_motion_dir is not None:
        camera_centers = _load_motion_camera(opts.human_motion_dir)
        if camera_centers is not None and len(camera_centers):
            colors = np.tile(np.array([[0.05, 0.70, 1.00]], dtype=np.float32), (len(camera_centers), 1))
            display_centers = camera_centers @ display_rot
            motion_handles.append(
                server.scene.add_point_cloud(
                    "/human_motion/camera_trajectory",
                    points=display_centers,
                    colors=colors,
                    point_size=opts.camera_traj_point_size,
                    point_shape="circle",
                )
            )

        if opts.show_human_points:
            palette = _palette().astype(np.float32) / 255.0
            for idx, (name, positions) in enumerate(_load_human_tracks(opts.human_motion_dir)):
                colors = np.tile(palette[idx % len(palette)][None, :], (len(positions), 1))
                display_positions = positions @ display_rot
                motion_handles.append(
                    server.scene.add_point_cloud(
                        f"/human_motion/humans/{name}/trajectory",
                        points=display_positions,
                        colors=colors,
                        point_size=opts.human_point_size,
                        point_shape="circle",
                    )
                )

        if opts.show_smpl_meshes:
            for name, vertices, faces, color in _load_smpl_meshes(
                opts.human_motion_dir,
                opts.smpl_model_dir,
                opts.mesh_sample_stride,
                opts.mesh_max_tracks,
                opts.mesh_max_frames_per_track,
            ):
                display_vertices = vertices @ display_rot
                mesh_handles.append(
                    server.scene.add_mesh_simple(
                        f"/human_motion/smpl/{name}",
                        vertices=display_vertices,
                        faces=faces,
                        color=color,
                        opacity=0.72,
                        material="standard",
                        side="double",
                    )
                )

    with server.gui.add_folder("Scene"):
        gui_show_points = server.gui.add_checkbox("Show points", True)
        gui_show_cameras = server.gui.add_checkbox("Show DUSt3R cameras", True)
        gui_show_motion = server.gui.add_checkbox("Show motion camera/points", True)
        gui_show_meshes = server.gui.add_checkbox("Show SMPL meshes", True)
        gui_point_size = server.gui.add_slider(
            "Point size",
            min=0.001,
            max=0.05,
            step=0.0005,
            initial_value=opts.point_size,
        )

        @gui_show_points.on_update
        def _(_: bool) -> None:
            for handle in point_handles:
                handle.visible = gui_show_points.value

        @gui_show_cameras.on_update
        def _(_: bool) -> None:
            for handle in camera_handles:
                handle.visible = gui_show_cameras.value

        @gui_show_motion.on_update
        def _(_: bool) -> None:
            for handle in motion_handles:
                handle.visible = gui_show_motion.value

        @gui_show_meshes.on_update
        def _(_: bool) -> None:
            for handle in mesh_handles:
                handle.visible = gui_show_meshes.value

        @gui_point_size.on_update
        def _(_: float) -> None:
            for handle in point_handles:
                handle.point_size = gui_point_size.value

    timer = server.gui.add_number("Elapsed (s)", 0.0, disabled=True)
    start = time.time()
    try:
        while True:
            time.sleep(0.05)
            timer.value = time.time() - start
    except KeyboardInterrupt:
        return


def main() -> None:
    visualize(tyro.cli(Options))


if __name__ == "__main__":
    main()
